domain: "felipe-higino.github.io"
url: "https://felipe-higino.github.io/"
# baseurl: ""

# please use TZ database name column on the list table
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone: ""

###########################################################
# Front Matter Defaults (https://jekyllrb.com/docs/configuration/front-matter-defaults/)
###########################################################
defaults:
  # for posts
  - scope:
      # to separate language posts folders
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:path

  # for multilingual posts
  - scope:
      # to separate language posts folders
      path: "*/_posts"
    values:
      hidden: true
      layout: "post"
      permalink: /:path

  # example: enable setting for all pages. You may still need to enable some setting from _data/conf/posts.yml or _data/conf/main.yml
  # - scope:
  #     # an empty string here means all files in the project
  #     path: ""
  #   values:
  #     image_viewer_on: true
  #     image_lazy_loader_on: true

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  auto_ids: true
  syntax_highlighter: rouge

kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# since GitHub Pages runs jekyll with "--safe" flag, we need to add supported plugins in here. (only github supported plugins are allowed)
whitelist:
  - jekyll-paginate
  - jekyll-redirect-from

paginate_path: "/tabs/blog/:num"
paginate: 5

redirect_from:
  json: false

compress_html:
  clippings: all
  comments: all
  #endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

compress_js:
  linebreak_and_space: false
  #ignore: development
sass:
  sass_dir: assets/_scss
  style: compressed

exclude: ["Gemfile*", "README*", "LICENSE", "docs"]
